### ISSUE TITLE
Model status?

### ISSUE THREAD

**Issue by GemmaTuron** [ersilia-os/eos8vud#4]
Hi @miquelduranfrigola 

What is the status of this model? Is it ready and just failing at building the Docker container?

**Comment by miquelduranfrigola** [comment]
It is not ready yet since it has many extra additions. I will update you asap

**Comment by miquelduranfrigola** [comment]
Hi @GemmaTuron this model has been added - although not heavily tested. I think it would make sense to try it in ChemSampler (DCA project)
